### PR TITLE
Updated conv.rs so that "Convolution done..." is only printed in debug builds

### PR DESCRIPTION
**Pull request by zeneiny**
I would really appreciate the ability to suppress image-conv's output to stdout. If I'm using image-conv as part of another project, I don't want to pollute the output of that other project whenever a convolution happens.
Thanks!

### CODE REVIEW

**Review by gp-97 — CHANGES_REQUESTED** [review]
Run rustfmt for CI. Rest looks good.

**Comment by gp-97** [comment]
@zeneiny Thanks for the changes. Just run rustfmt for the CI.

**Comment by zeneiny** [comment]
@gp-97 Thanks, done!

**Comment by gp-97** [comment]
Great !!!. Looks good. Going to merge

**Pull request merged**
